//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ArchFile.g by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ArchFileParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IArchFileListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] ArchFileParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] ArchFileParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.arch_ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArch_ident([NotNull] ArchFileParser.Arch_identContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.arch_ident"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArch_ident([NotNull] ArchFileParser.Arch_identContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDef([NotNull] ArchFileParser.DefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDef([NotNull] ArchFileParser.DefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.isa_block_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsa_block_def([NotNull] ArchFileParser.Isa_block_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.isa_block_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsa_block_def([NotNull] ArchFileParser.Isa_block_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.format_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormat_def([NotNull] ArchFileParser.Format_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.format_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormat_def([NotNull] ArchFileParser.Format_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.format_field_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormat_field_def([NotNull] ArchFileParser.Format_field_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.format_field_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormat_field_def([NotNull] ArchFileParser.Format_field_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.regspace_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegspace_def([NotNull] ArchFileParser.Regspace_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.regspace_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegspace_def([NotNull] ArchFileParser.Regspace_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.reg_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReg_def([NotNull] ArchFileParser.Reg_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.reg_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReg_def([NotNull] ArchFileParser.Reg_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.reg_bank_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReg_bank_def([NotNull] ArchFileParser.Reg_bank_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.reg_bank_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReg_bank_def([NotNull] ArchFileParser.Reg_bank_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.reg_slot_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReg_slot_def([NotNull] ArchFileParser.Reg_slot_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.reg_slot_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReg_slot_def([NotNull] ArchFileParser.Reg_slot_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.behaviour_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBehaviour_def([NotNull] ArchFileParser.Behaviour_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.behaviour_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBehaviour_def([NotNull] ArchFileParser.Behaviour_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.helper_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHelper_def([NotNull] ArchFileParser.Helper_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.helper_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHelper_def([NotNull] ArchFileParser.Helper_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrototype([NotNull] ArchFileParser.PrototypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrototype([NotNull] ArchFileParser.PrototypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_list([NotNull] ArchFileParser.Parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_list([NotNull] ArchFileParser.Parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttr([NotNull] ArchFileParser.AttrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.attr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttr([NotNull] ArchFileParser.AttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] ArchFileParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] ArchFileParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.fnbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFnbody([NotNull] ArchFileParser.FnbodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.fnbody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFnbody([NotNull] ArchFileParser.FnbodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ArchFileParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ArchFileParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_statement([NotNull] ArchFileParser.Expression_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_statement([NotNull] ArchFileParser.Expression_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.flow_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFlow_statement([NotNull] ArchFileParser.Flow_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.flow_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFlow_statement([NotNull] ArchFileParser.Flow_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIteration_statement([NotNull] ArchFileParser.Iteration_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIteration_statement([NotNull] ArchFileParser.Iteration_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection_statement([NotNull] ArchFileParser.Selection_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection_statement([NotNull] ArchFileParser.Selection_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_statement([NotNull] ArchFileParser.If_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_statement([NotNull] ArchFileParser.If_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_statement([NotNull] ArchFileParser.Switch_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_statement([NotNull] ArchFileParser.Switch_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ArchFileParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ArchFileParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.constant_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant_expr([NotNull] ArchFileParser.Constant_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.constant_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant_expr([NotNull] ArchFileParser.Constant_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument_list([NotNull] ArchFileParser.Argument_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument_list([NotNull] ArchFileParser.Argument_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.constant_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant_number([NotNull] ArchFileParser.Constant_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.constant_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant_number([NotNull] ArchFileParser.Constant_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] ArchFileParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] ArchFileParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary_expression([NotNull] ArchFileParser.Primary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary_expression([NotNull] ArchFileParser.Primary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_expression([NotNull] ArchFileParser.Call_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.call_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_expression([NotNull] ArchFileParser.Call_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_operator([NotNull] ArchFileParser.Unary_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_operator([NotNull] ArchFileParser.Unary_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_expression([NotNull] ArchFileParser.Postfix_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_expression([NotNull] ArchFileParser.Postfix_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.postfix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_operator([NotNull] ArchFileParser.Postfix_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.postfix_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_operator([NotNull] ArchFileParser.Postfix_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] ArchFileParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] ArchFileParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expression([NotNull] ArchFileParser.Unary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expression([NotNull] ArchFileParser.Unary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLvalue([NotNull] ArchFileParser.LvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLvalue([NotNull] ArchFileParser.LvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.full_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFull_assignment_expression([NotNull] ArchFileParser.Full_assignment_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.full_assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFull_assignment_expression([NotNull] ArchFileParser.Full_assignment_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_operator([NotNull] ArchFileParser.Assignment_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_operator([NotNull] ArchFileParser.Assignment_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.ternary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTernary_expression([NotNull] ArchFileParser.Ternary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.ternary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTernary_expression([NotNull] ArchFileParser.Ternary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.log_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLog_or_expression([NotNull] ArchFileParser.Log_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.log_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLog_or_expression([NotNull] ArchFileParser.Log_or_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.log_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLog_and_expression([NotNull] ArchFileParser.Log_and_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.log_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLog_and_expression([NotNull] ArchFileParser.Log_and_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.bit_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBit_or_expression([NotNull] ArchFileParser.Bit_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.bit_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBit_or_expression([NotNull] ArchFileParser.Bit_or_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.bit_xor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBit_xor_expression([NotNull] ArchFileParser.Bit_xor_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.bit_xor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBit_xor_expression([NotNull] ArchFileParser.Bit_xor_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.bit_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBit_and_expression([NotNull] ArchFileParser.Bit_and_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.bit_and_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBit_and_expression([NotNull] ArchFileParser.Bit_and_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality_expression([NotNull] ArchFileParser.Equality_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.equality_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality_expression([NotNull] ArchFileParser.Equality_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.comparison_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison_expression([NotNull] ArchFileParser.Comparison_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.comparison_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison_expression([NotNull] ArchFileParser.Comparison_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_expression([NotNull] ArchFileParser.Shift_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_expression([NotNull] ArchFileParser.Shift_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.add_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_expression([NotNull] ArchFileParser.Add_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.add_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_expression([NotNull] ArchFileParser.Add_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.mult_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult_expression([NotNull] ArchFileParser.Mult_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.mult_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult_expression([NotNull] ArchFileParser.Mult_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.cast_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCast_expression([NotNull] ArchFileParser.Cast_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.cast_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCast_expression([NotNull] ArchFileParser.Cast_expressionContext context);
}
