//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ArchFile.g by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IArchFileListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class ArchFileBaseListener : IArchFileListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] ArchFileParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] ArchFileParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.arch_ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArch_ident([NotNull] ArchFileParser.Arch_identContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.arch_ident"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArch_ident([NotNull] ArchFileParser.Arch_identContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDef([NotNull] ArchFileParser.DefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDef([NotNull] ArchFileParser.DefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.isa_block_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIsa_block_def([NotNull] ArchFileParser.Isa_block_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.isa_block_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIsa_block_def([NotNull] ArchFileParser.Isa_block_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.format_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormat_def([NotNull] ArchFileParser.Format_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.format_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormat_def([NotNull] ArchFileParser.Format_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.format_field_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormat_field_def([NotNull] ArchFileParser.Format_field_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.format_field_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormat_field_def([NotNull] ArchFileParser.Format_field_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.behaviour_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBehaviour_def([NotNull] ArchFileParser.Behaviour_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.behaviour_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBehaviour_def([NotNull] ArchFileParser.Behaviour_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.helper_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHelper_def([NotNull] ArchFileParser.Helper_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.helper_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHelper_def([NotNull] ArchFileParser.Helper_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.prototype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrototype([NotNull] ArchFileParser.PrototypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.prototype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrototype([NotNull] ArchFileParser.PrototypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_list([NotNull] ArchFileParser.Parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_list([NotNull] ArchFileParser.Parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttr([NotNull] ArchFileParser.AttrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttr([NotNull] ArchFileParser.AttrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] ArchFileParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] ArchFileParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.fnbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFnbody([NotNull] ArchFileParser.FnbodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.fnbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFnbody([NotNull] ArchFileParser.FnbodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ArchFileParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ArchFileParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_statement([NotNull] ArchFileParser.Expression_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_statement([NotNull] ArchFileParser.Expression_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.flow_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlow_statement([NotNull] ArchFileParser.Flow_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.flow_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlow_statement([NotNull] ArchFileParser.Flow_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.iteration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIteration_statement([NotNull] ArchFileParser.Iteration_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.iteration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIteration_statement([NotNull] ArchFileParser.Iteration_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.selection_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection_statement([NotNull] ArchFileParser.Selection_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.selection_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection_statement([NotNull] ArchFileParser.Selection_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_statement([NotNull] ArchFileParser.If_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.if_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_statement([NotNull] ArchFileParser.If_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.switch_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_statement([NotNull] ArchFileParser.Switch_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.switch_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_statement([NotNull] ArchFileParser.Switch_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ArchFileParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ArchFileParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.constant_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant_expr([NotNull] ArchFileParser.Constant_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.constant_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant_expr([NotNull] ArchFileParser.Constant_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument_list([NotNull] ArchFileParser.Argument_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.argument_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument_list([NotNull] ArchFileParser.Argument_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] ArchFileParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] ArchFileParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expression([NotNull] ArchFileParser.Primary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expression([NotNull] ArchFileParser.Primary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_expression([NotNull] ArchFileParser.Call_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.call_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_expression([NotNull] ArchFileParser.Call_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_operator([NotNull] ArchFileParser.Unary_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_operator([NotNull] ArchFileParser.Unary_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_expression([NotNull] ArchFileParser.Postfix_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_expression([NotNull] ArchFileParser.Postfix_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.postfix_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_operator([NotNull] ArchFileParser.Postfix_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.postfix_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_operator([NotNull] ArchFileParser.Postfix_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] ArchFileParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] ArchFileParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expression([NotNull] ArchFileParser.Unary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expression([NotNull] ArchFileParser.Unary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLvalue([NotNull] ArchFileParser.LvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLvalue([NotNull] ArchFileParser.LvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.full_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFull_assignment_expression([NotNull] ArchFileParser.Full_assignment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.full_assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFull_assignment_expression([NotNull] ArchFileParser.Full_assignment_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_operator([NotNull] ArchFileParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_operator([NotNull] ArchFileParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.ternary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTernary_expression([NotNull] ArchFileParser.Ternary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.ternary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTernary_expression([NotNull] ArchFileParser.Ternary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.log_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLog_or_expression([NotNull] ArchFileParser.Log_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.log_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLog_or_expression([NotNull] ArchFileParser.Log_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.log_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLog_and_expression([NotNull] ArchFileParser.Log_and_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.log_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLog_and_expression([NotNull] ArchFileParser.Log_and_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.bit_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBit_or_expression([NotNull] ArchFileParser.Bit_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.bit_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBit_or_expression([NotNull] ArchFileParser.Bit_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.bit_xor_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBit_xor_expression([NotNull] ArchFileParser.Bit_xor_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.bit_xor_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBit_xor_expression([NotNull] ArchFileParser.Bit_xor_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.bit_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBit_and_expression([NotNull] ArchFileParser.Bit_and_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.bit_and_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBit_and_expression([NotNull] ArchFileParser.Bit_and_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEquality_expression([NotNull] ArchFileParser.Equality_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.equality_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEquality_expression([NotNull] ArchFileParser.Equality_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.comparison_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison_expression([NotNull] ArchFileParser.Comparison_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.comparison_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison_expression([NotNull] ArchFileParser.Comparison_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_expression([NotNull] ArchFileParser.Shift_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.shift_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_expression([NotNull] ArchFileParser.Shift_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.add_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_expression([NotNull] ArchFileParser.Add_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.add_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_expression([NotNull] ArchFileParser.Add_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.mult_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult_expression([NotNull] ArchFileParser.Mult_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.mult_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult_expression([NotNull] ArchFileParser.Mult_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ArchFileParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCast_expression([NotNull] ArchFileParser.Cast_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ArchFileParser.cast_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCast_expression([NotNull] ArchFileParser.Cast_expressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
